
version: "3"
services:
  miraiok:
    network_mode: "host"
    image: oicq:v1
    restart: always
    volumes:
      - ./config.js:/root/config.js
      - ./data:/root/data
    stdin_open: true
    tty: true
    container_name: docker-oicq
    
