name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
      
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"
        
        with:
          version: latest
      - name: build the image
        run: docker oicq build --push \
            --tag lhpmain/docker-oicq:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .


