name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
      
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install oicq
        id: oicq
        uses: lhpmain/docker-oicq@v1
        with:
          version: latest
      - name: build the image
        run: docker oicq build --push \
            --tag lhpmain/docker-oicq:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .


